apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: "web-port"
      containerPort: 80 
# kubectl port-forward my-pod 8080:80 komutuyla host makinaya maplenebilir. Debugging için kullanılır.