apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    args: #[ "date" ]
    - "date"
    # kubectl logs my-pod komutuyla loglardan date'in çalıştığını görebiliriz.


